const properties = [
    {
        id: 1,
        title: "2 BHK Apartment in Andheri",
        location: "Andheri, Mumbai",
        type: "rent",
        price: "₹35,000/month",
        details: "Spacious flat with amenities, near metro station.",
        status: "rent",
        bedrooms: "2BHK",
        furnishing: "semi",
        img: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80"
    },
    {
        id: 2,
        title: "3 BHK Villa in Whitefield",
        location: "Whitefield, Bangalore",
        type: "buy",
        price: "₹1.2 Crore",
        details: "Luxury villa with garden, gated community.",
        status: "buy",
        bedrooms: "3BHK",
        furnishing: "full",
        img: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80"
    },
    {
        id: 3,
        title: "1 BHK Studio in Hinjewadi",
        location: "Hinjewadi, Pune",
        type: "rent",
        price: "₹18,000/month",
        details: "Ideal for singles, close to IT park.",
        status: "rent",
        bedrooms: "1RK",
        furnishing: "semi",
        img: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80"
    },
    {
        id: 4,
        title: "4 BHK Penthouse in Golf Course Road",
        location: "Golf Course Road, Gurgaon",
        type: "buy",
        price: "₹3.5 Crore",
        details: "Premium penthouse with city view.",
        status: "buy",
        bedrooms: "4+BHK",
        furnishing: "full",
        img: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80"
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Golf Course Road, Gurgaon',
        price:35000,
        title:'2 BHK Flat in Gurgaon',
        details:'2BHK, 1200 sqft, Semi Furnished, City View',
        img:'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Andheri, Mumbai',
        price:45000,
        title:'Luxury Apartment in Mumbai',
        details:'3BHK, 1800 sqft, Fully Furnished, Pool, Gym, Parking',
        img:'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'semi',
        location:'Whitefield, Bangalore',
        price:65000,
        title:'Modern Villa in Bangalore',
        details:'4BHK, 3200 sqft, Semi Furnished, Garden, Security',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'penthouse',
        bedrooms:'4+BHK',
        furnishing:'full',
        location:'Golf Course Road, Gurgaon',
        price:120000,
        title:'Penthouse in Gurgaon',
        details:'5BHK, 3500 sqft, Fully Furnished, City View',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'3BHK',
        furnishing:'none',
        location:'Dwarka, Delhi',
        price:39000,
        title:'Premium Apartment in Delhi',
        details:'3BHK, 1600 sqft, Unfurnished, Pool, Gym',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Thane, Mumbai',
        price:42000,
        title:'Skyline Towers',
        details:'2BHK, 1100 sqft, Semi Furnished, Smart Homes, Clubhouse',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'independent',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Gachibowli, Hyderabad',
        price:38000,
        title:'Independent House in Hyderabad',
        details:'3BHK, 2000 sqft, Fully Furnished, East Facing',
        img:'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'farmhouse',
        bedrooms:'4+BHK',
        furnishing:'semi',
        location:'Malviya Nagar, Jaipur',
        price:25000,
        title:'Farm House in Jaipur',
        details:'5BHK, 2400 sqft, Semi Furnished, East Facing',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'none',
        location:'Bannerghatta, Bangalore',
        price:55000,
        title:'Green Meadows',
        details:'4BHK, 3200 sqft, Unfurnished, Villas, Clubhouse',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'1RK',
        furnishing:'semi',
        location:'Hinjewadi, Pune',
        price:18000,
        title:'Studio Apartment in Pune',
        details:'1RK, 600 sqft, Semi Furnished, Near IT Park',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'full',
        location:'Jubilee Hills, Hyderabad',
        price:50000,
        title:'Apartment in Jubilee Hills',
        details:'2BHK, 1200 sqft, Fully Furnished, Pool',
        img:'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'independent',
        bedrooms:'3BHK',
        furnishing:'semi',
        location:'Hitech City, Hyderabad',
        price:35000,
        title:'House in Hitech City',
        details:'3BHK, 1800 sqft, Semi Furnished, Parking',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'none',
        location:'Banjara Hills, Hyderabad',
        price:60000,
        title:'Villa in Banjara Hills',
        details:'4BHK, 4000 sqft, Unfurnished, Garden',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Kondapur, Hyderabad',
        price:32000,
        title:'Apartment in Kondapur',
        details:'2BHK, 1100 sqft, Semi Furnished, Gym',
        img:'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'independent',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Madhapur, Hyderabad',
        price:40000,
        title:'House in Madhapur',
        details:'3BHK, 2000 sqft, Fully Furnished, East Facing',
        img:'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'1RK',
        furnishing:'none',
        location:'Manikonda, Hyderabad',
        price:15000,
        title:'Studio in Manikonda',
        details:'1RK, 500 sqft, Unfurnished, Near IT Park',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'semi',
        location:'Shamshabad, Hyderabad',
        price:35000,
        title:'Villa in Shamshabad',
        details:'4BHK, 3500 sqft, Semi Furnished, Garden',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Begumpet, Hyderabad',
        price:42000,
        title:'Apartment in Begumpet',
        details:'3BHK, 1600 sqft, Fully Furnished, Pool',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'independent',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Secunderabad, Hyderabad',
        price:25000,
        title:'House in Secunderabad',
        details:'2BHK, 1200 sqft, Semi Furnished, Parking',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'rent'
    },
    {
        type:'apartment',
        bedrooms:'3BHK',
        furnishing:'semi',
        location:'Andheri, Mumbai',
        price:25000000,
        title:'Luxury Apartment in Mumbai',
        details:'3BHK, 1800 sqft, Semi Furnished, Pool, Gym, Parking',
        img:'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'full',
        location:'Whitefield, Bangalore',
        price:38000000,
        title:'Modern Villa in Bangalore',
        details:'4BHK, 3200 sqft, Fully Furnished, Garden, Security',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'penthouse',
        bedrooms:'4+BHK',
        furnishing:'full',
        location:'Golf Course Road, Gurgaon',
        price:42000000,
        title:'Penthouse in Gurgaon',
        details:'5BHK, 3500 sqft, Fully Furnished, City View',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'OMR, Chennai',
        price:16000000,
        title:'Premium Apartment in Chennai',
        details:'2BHK, 1500 sqft, Semi Furnished, Pool, Gym',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'none',
        location:'Koregaon Park, Pune',
        price:11000000,
        title:'2 BHK Flat in Pune',
        details:'2BHK, 1100 sqft, Unfurnished, Balcony',
        img:'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'independent',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Gachibowli, Hyderabad',
        price:22000000,
        title:'Independent House in Hyderabad',
        details:'3BHK, 2000 sqft, Fully Furnished, East Facing',
        img:'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'semi',
        location:'Bannerghatta, Bangalore',
        price:22000000,
        title:'Green Meadows',
        details:'4BHK, 3200 sqft, Semi Furnished, Villas, Clubhouse',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'1RK',
        furnishing:'semi',
        location:'Thane, Mumbai',
        price:11000000,
        title:'Skyline Towers',
        details:'1RK, 600 sqft, Semi Furnished, Smart Homes, Clubhouse',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'3BHK',
        furnishing:'none',
        location:'Dwarka, Delhi',
        price:18000000,
        title:'Premium Apartment in Delhi',
        details:'3BHK, 1600 sqft, Unfurnished, Pool, Gym',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'full',
        location:'Jubilee Hills, Hyderabad',
        price:35000000,
        title:'Villa in Jubilee Hills',
        details:'4BHK, 4000 sqft, Fully Furnished, Garden',
        img:'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Hitech City, Hyderabad',
        price:17000000,
        title:'Apartment in Hitech City',
        details:'2BHK, 1200 sqft, Semi Furnished, Pool',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'independent',
        bedrooms:'3BHK',
        furnishing:'none',
        location:'Banjara Hills, Hyderabad',
        price:21000000,
        title:'House in Banjara Hills',
        details:'3BHK, 1800 sqft, Unfurnished, Parking',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'villa',
        bedrooms:'4+BHK',
        furnishing:'full',
        location:'Kondapur, Hyderabad',
        price:40000000,
        title:'Luxury Villa in Kondapur',
        details:'5BHK, 5000 sqft, Fully Furnished, Pool',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Madhapur, Hyderabad',
        price:15000000,
        title:'Apartment in Madhapur',
        details:'2BHK, 1100 sqft, Semi Furnished, Gym',
        img:'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'independent',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Manikonda, Hyderabad',
        price:23000000,
        title:'House in Manikonda',
        details:'3BHK, 2000 sqft, Fully Furnished, East Facing',
        img:'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'1RK',
        furnishing:'none',
        location:'Shamshabad, Hyderabad',
        price:9000000,
        title:'Studio in Shamshabad',
        details:'1RK, 500 sqft, Unfurnished, Near Airport',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'villa',
        bedrooms:'4BHK',
        furnishing:'semi',
        location:'Begumpet, Hyderabad',
        price:27000000,
        title:'Villa in Begumpet',
        details:'4BHK, 3500 sqft, Semi Furnished, Garden',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'apartment',
        bedrooms:'3BHK',
        furnishing:'full',
        location:'Secunderabad, Hyderabad',
        price:20000000,
        title:'Apartment in Secunderabad',
        details:'3BHK, 1600 sqft, Fully Furnished, Pool',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'independent',
        bedrooms:'2BHK',
        furnishing:'semi',
        location:'Gachibowli, Hyderabad',
        price:15000000,
        title:'House in Gachibowli',
        details:'2BHK, 1200 sqft, Semi Furnished, Parking',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        status: 'buy'
    },
    {
        type:'office',
        bedrooms:'NA',
        furnishing:'semi',
        location:'Sector 62, Noida',
        price:120000,
        title:'Office Space in Noida',
        details:'2000 sqft, Semi Furnished, Parking',
        img:'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'business',
        bedrooms:'NA',
        furnishing:'full',
        location:'BKC, Mumbai',
        price:250000,
        title:'Business Center in Mumbai',
        details:'3500 sqft, Fully Furnished, Conference Rooms',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'retail',
        bedrooms:'NA',
        furnishing:'semi',
        location:'MG Road, Bangalore',
        price:180000,
        title:'Retail Space in Bangalore',
        details:'1800 sqft, Semi Furnished, High Footfall',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'office',
        bedrooms:'NA',
        furnishing:'full',
        location:'Hinjewadi, Pune',
        price:210000,
        title:'IT Park Office in Pune',
        details:'2200 sqft, Fully Furnished, Cafeteria',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'retail',
        bedrooms:'NA',
        furnishing:'none',
        location:'T Nagar, Chennai',
        price:150000,
        title:'Showroom in Chennai',
        details:'1600 sqft, Unfurnished, Main Road',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'warehouse',
        bedrooms:'NA',
        furnishing:'semi',
        location:'Shamshabad, Hyderabad',
        price:110000,
        title:'Warehouse in Hyderabad',
        details:'3000 sqft, Semi Furnished, Loading Bay',
        img:'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'office',
        bedrooms:'NA',
        furnishing:'full',
        location:'Cyber City, Gurgaon',
        price:280000,
        title:'Corporate Office in Gurgaon',
        details:'4000 sqft, Fully Furnished, Security',
        img:'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'business',
        bedrooms:'NA',
        furnishing:'semi',
        location:'C Scheme, Jaipur',
        price:130000,
        title:'Business Hub in Jaipur',
        details:'1700 sqft, Semi Furnished, Parking',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'retail',
        bedrooms:'NA',
        furnishing:'full',
        location:'Saket, Delhi',
        price:220000,
        title:'Retail Mall in Delhi',
        details:'2500 sqft, Fully Furnished, Food Court',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'office',
        bedrooms:'NA',
        furnishing:'none',
        location:'Koramangala, Bangalore',
        price:160000,
        title:'Startup Space in Bangalore',
        details:'1200 sqft, Unfurnished, Meeting Rooms',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'coworking',
        bedrooms:'NA',
        furnishing:'full',
        location:'Hitech City, Hyderabad',
        price:90000,
        title:'Co-Working Space in Hyderabad',
        details:'1000 sqft, Fully Furnished, Flexible Desks',
        img:'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'food',
        bedrooms:'NA',
        furnishing:'semi',
        location:'Jubilee Hills, Hyderabad',
        price:120000,
        title:'Restaurant Space in Hyderabad',
        details:'1500 sqft, Semi Furnished, Prime Location',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'health',
        bedrooms:'NA',
        furnishing:'full',
        location:'Banjara Hills, Hyderabad',
        price:130000,
        title:'Clinic Space in Hyderabad',
        details:'1200 sqft, Fully Furnished, Parking',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'automotive',
        bedrooms:'NA',
        furnishing:'none',
        location:'Begumpet, Hyderabad',
        price:80000,
        title:'Auto Service Center',
        details:'2000 sqft, Unfurnished, Main Road',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'education',
        bedrooms:'NA',
        furnishing:'semi',
        location:'Secunderabad, Hyderabad',
        price:110000,
        title:'Coaching Center',
        details:'1800 sqft, Semi Furnished, Near Metro',
        img:'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'beauty',
        bedrooms:'NA',
        furnishing:'full',
        location:'Kondapur, Hyderabad',
        price:95000,
        title:'Salon Space',
        details:'900 sqft, Fully Furnished, High Footfall',
        img:'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'entertainment',
        bedrooms:'NA',
        furnishing:'semi',
        location:'Madhapur, Hyderabad',
        price:105000,
        title:'Game Zone',
        details:'1200 sqft, Semi Furnished, Parking',
        img:'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'financial',
        bedrooms:'NA',
        furnishing:'full',
        location:'Manikonda, Hyderabad',
        price:115000,
        title:'Bank Branch',
        details:'1500 sqft, Fully Furnished, Security',
        img:'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'technology',
        bedrooms:'NA',
        furnishing:'none',
        location:'Shamshabad, Hyderabad',
        price:125000,
        title:'IT Startup Office',
        details:'1100 sqft, Unfurnished, Near Airport',
        img:'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    },
    {
        type:'misc',
        bedrooms:'NA',
        furnishing:'semi',
        location:'Gachibowli, Hyderabad',
        price:95000,
        title:'Miscellaneous Space',
        details:'1000 sqft, Semi Furnished, Flexible Use',
        img:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=400&q=80',
        category: 'commercial',
        status: 'rent'
    }
];